openapi: 3.0.0
info:
  title: GDI GraphQL APIs
  description: Some simple APIs for GDI exploring GraphQL
  version: 1.0.0
paths:
  /alarm/graphql:
    post:
      operationId: alarmGql
      summary: "GraphQL endpoint for alarms"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GraphQLQuery"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GraphQLResponse"
  /localfs/graphql:
    post:
      operationId: localfsGql
      summary: "GraphQL endpoint for server local  - POC PURPOSES ONLY"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GraphQLQuery"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GraphQLResponse"
components:
  schemas:
    GraphQLQuery:
      type: object
      required:
        - query
      properties:
        query:
          type: string
        parameters:
          type: object
    GraphQLResponse:
      type: object
      properties:
        data:
          type: object